### ISSUE TITLE
Version range of package import for org.osgi.service.log to strict

### ISSUE THREAD

**Issue by tobias-hammerschmidt** [osgi/slf4j-osgi#70]
I want to use this fragment within a RCP application based on Eclipse 4.18. The included equinox runtime seems to implement the osgi log service version 1.5. Since the package import directive for org.osgi.service.log in slf4j.osgi is stated as [1.4,1.5) the fragment fails to resolve in my context. Looking at the source code and the documentation at https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.log.html#org.osgi.service.log I'm wondering why the version range is so strict.? To my understanding this fragment only consumes the log service api so according to the documentation a version range of [1.4,2.0) should be fine.

**Comment by bjhargrave** [comment]
The narrow version range is used because the code [implements `org.osgi.service.log.Logger`](https://github.com/osgi/slf4j-osgi/blob/80cd2e6483af4333c91347e3dc8060af72123e0a/src/main/java/org/slf4j/impl/SLF4JLogger.java#L284-L287). Because the code "provides" the log API, Bnd will use the provider's narrow version range.

I will look at changing the implementation of `StubLogger` to use reflection instead of directly implementing `org.osgi.service.log.Logger` to enable the use of a wider import range.

**Comment by tobias-hammerschmidt** [comment]
Ah I missed the `StubLogger`, thanks for the explanation and also for the prompt fix :+1:

**Comment by bjhargrave** [comment]
slf4j.osgi-1.7.1 is now released to Maven Central.
